WebMinePlus/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------
#             Chuly
#     GitHub: https://github.com/victoryanezn
#     Discord: chuly2005#0
# ---------------------------------- 

app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name= "home"),
    path('contacto/', views.contacto, name= "contacto"),
    path('reglas/', views.reglas, name= "reglas"),
    path('tienda/', views.tienda, name= "tienda"),
    path('agregar-producto/', views.agregar_producto, name="agregar_producto"),
    path('listar-productos/', views.listar_productos, name="listar_productos"),
    path('modificar-productos/<id>/', views.modificar_producto, name="modificar_productos"),
    path('eliminar-producto/<id>/', views.eliminar_producto, name="eliminar_producto"),
    path('registro/', views.registro, name ="registro"),
    path('feedbacks/', views.feedbacks, name ="feedbacks"),

    # --
    path('agregar-feedback/', views.agregar_feedback, name="agregar_feedback"),
    path('listar-feedbacks/', views.listar_feedbacks, name="listar_feedbacks"),
    path('modificar-feedbacks/<id>/', views.modificar_feedback, name="modificar_feedbacks"),
    path('eliminar-feedback/<id>/', views.eliminar_feedback, name="eliminar_feedback"),
    

]

# ----------------------------------
#             Chuly
#     GitHub: https://github.com/victoryanezn
#     Discord: chuly2005#0
# ---------------------------------- 

app/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.

class Tipo(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT, verbose_name="Tipo")
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre
    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="NOMBRE:")
    correo = models.EmailField(verbose_name="CORREO:")
    mensaje = models.TextField(verbose_name="MENSAJE:")
    
    def __str__(self):
        return self.nombre
    


class Feedback(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    autor = models.CharField(max_length=10)  # Añadir campo autor
    fecha_creado = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo
    


# ----------------------------------
#             Chuly
#     GitHub: https://github.com/victoryanezn
#     Discord: chuly2005#0
# ---------------------------------- 

app/templates/app/Feedback/agregar.html
{% extends 'app/base.html' %}



{% load crispy_forms_tags %}
{% block contenido %}
<br><br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="formu">
                <div class="card-body ">
                    <h2 class="text-dark text-center">Nuevo Feedback</h2>
                    <hr class="text-dark">
                    <br>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class=" d-flex text-center justify-content-end">
                            <input type="reset" value="Limpiar" class="btn btn-light">
                            &nbsp;
                            <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
                            
                            &nbsp;
                            <input type="submit" value="Guardar" class="btn btn-primary">
                        </div>
                    </form>
                    {{mensaje}}
                </div>  
            </div>

        </div>
    </div>
</div>
<br><br><br>

{% endblock %}


{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}

app/templates/app/Feedback/listar.html
{% extends 'app/base.html' %}

{% block js %}

<script>
    function eliminar_feedback(id){
        Swal.fire({
            "title":"¿Estas seguro?",
            "text": "Esta acción no se puede deshacer",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText": "No, Cancelar",
            "confirmButtonText": "Si, Eliminar",
            "reverseButtons": true,
            "confirmButtonColor": "#dc3545",
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href="/eliminar-feedback/"+id+"/"
            }
        })
    }
</script>

{% endblock %}

{% block contenido %}
{% load humanize %}


<br><br><br><br> <br><br>
<div class="container ">
    <div class="formu">
        <div class="card-body">
            <h2 class="text-dark text-center">Listado de Feedbacks</h2>
            <hr class="text-dark">
            <table class="table table-striped table-responsive  table-responsive">
                <thead>
                    <tr>
                    <th>Fecha</th>
                    <th>Autor</th>
                    <th>Descipcion</th>

                    {% if perms.app.change_feedback or perms.app.delete_feedback %}       
                    <th>Opciones</th>
                    {% endif%}
                    </tr>
                </thead>
                <tbody >
                    {% for p in feedbacks %}
                    <tr>
                    <td>{{ p.fecha_creado }}</td>
                    <td>{{ p.autor | title }}</td>
                    <td style="word-break: break-all; overflow-wrap: break-word;">{{ p.descripcion }}</td>
                    <td>
                        {% if perms.app.change_feedback %}
                        <a href="{% url 'modificar_feedbacks' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                        {% endif %}
                        {% if perms.app.delete_feedback %}
                        <a href="#" onclick="eliminar_feedback({{p.id}})" class="btn btn-danger btn-sm">Eliminar</a>
                        {% endif %}
                    </td>
                </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>





{% endblock %}


{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}

app/templates/app/Feedback/modificar.html
{% extends 'app/base.html' %}


{% load crispy_forms_tags %}
{% block contenido %}
<br><br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="formu">
                <div class="card-body">
                    <h2 class="text-dark text-center">Editar Feedback</h2>
                    <hr class="text-dark">
                    <br>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class=" d-flex text-center justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="Editar" class="btn btn-primary">
                        </div>
                    </form>
                    {{mensaje}}
                </div>  
            </div>

        </div>
    </div>
</div>
<br><br><br>

{% endblock %}


{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}