WebMinePlus/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------
#             Chuly
#     GitHub: https://github.com/victoryanezn
#     Discord: chuly2005#0
# ---------------------------------- 

app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name= "home"),
    path('contacto/', views.contacto, name= "contacto"),
    path('reglas/', views.reglas, name= "reglas"),
    path('tienda/', views.tienda, name= "tienda"),
    path('agregar-producto/', views.agregar_producto, name="agregar_producto"),
    path('listar-productos/', views.listar_productos, name="listar_productos"),
    path('modificar-productos/<id>/', views.modificar_producto, name="modificar_productos"),
    path('eliminar-producto/<id>/', views.eliminar_producto, name="eliminar_producto"),
    path('registro/', views.registro, name ="registro"),
    path('feedbacks/', views.feedbacks, name ="feedbacks"),

    # --
    path('agregar-feedback/', views.agregar_feedback, name="agregar_feedback"),
    path('listar-feedbacks/', views.listar_feedbacks, name="listar_feedbacks"),
    path('modificar-feedbacks/<id>/', views.modificar_feedback, name="modificar_feedbacks"),
    path('eliminar-feedback/<id>/', views.eliminar_feedback, name="eliminar_feedback"),
    

]

# ----------------------------------
#             Chuly
#     GitHub: https://github.com/victoryanezn
#     Discord: chuly2005#0
# ---------------------------------- 

app/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.

class Tipo(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT, verbose_name="Tipo")
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre
    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="NOMBRE:")
    correo = models.EmailField(verbose_name="CORREO:")
    mensaje = models.TextField(verbose_name="MENSAJE:")
    
    def __str__(self):
        return self.nombre
    


class Feedback(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    autor = models.CharField(max_length=10)  # Añadir campo autor
    fecha_creado = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo
    


# ----------------------------------
#             Chuly
#     GitHub: https://github.com/victoryanezn
#     Discord: chuly2005#0
# ---------------------------------- 

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static%} 

    {% block css%}
    
    {% endblock %}
  
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'app/img/logos/logo 50x60 aprox.png' %}">
    
    
    <link rel="stylesheet" href="{% static 'app/css/estilos.css'%}">


       
    
    
    

    <title>MINEPLUS MC</title>
</head>
<body>
    <nav class="navbar navbar-dark  navbar-expand-md mb-5">
        <div class="container">
            <!-- <a href="{% url 'home' %}" class="navbar-brand p-0" id="logo-principal">
                <img src="{% static 'app/img/logo.png' %}" width="auto" height="100%" alt="logo-principal">
            </a> -->
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#menu-principal">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menu-principal">
                <ul class="navbar-nav">
                    <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Inicio</a></li>
                    <li class="nav-item"><a href="{% url 'reglas' %}" class="nav-link">Reglas</a></li>
                    <li class="nav-item"><a href="{% url 'feedbacks' %}" class="nav-link">Feedbacks</a></li>
                    <li class="nav-item"><a href="{% url 'contacto' %}" class="nav-link">Contacto</a></li>
                    <li class="nav-item"><a href="{% url 'tienda' %}" class="nav-link">Tienda</a></li>


                    {% if request.user.is_staff %}
                    <li class="nav-item dropdown">
                      <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                      >
                        Administracion
                      </a>
                      <ul class="dropdown-menu">
                        {% if perms.app.add_producto %}
                            <li class="nav-item"><a href="{% url 'agregar_producto' %}" class="nav-link">Agregar Producto</a></li>
                        {% endif %}
                        {% if perms.app.view_producto %}
                            <li class="nav-item"><a href="{% url 'listar_productos' %}" class="nav-link">Listado de Productos</a></li>
                        {% endif %}
                        {% if perms.app.view_feedbacks %}
                            <li class="nav-item"><a href="{% url 'listar_feedbacks' %}" class="nav-link">Listado de Feedbacks</a></li>
                        {% endif %}
                      </ul>
                    </li>
                    {% endif %}




                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'logout' %}" class="nav-link" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Cerrar Sesión</a>
                            <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                                {% csrf_token %}
                            </form>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">@{{ user.username | title }}</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Iniciar Sesión</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    {% block contenido %}

    {% endblock%}
    <br><br><br><br><br><br>
    <footer class="container-fluid text-white text-center bg-dark fixed-bottom mt-5">
        <div class="row py-2" id="footer">
            <div class="col-4 order-1">
                <a href="https://discord.gg/mineplusmc" target="_blank">
                    <img src="{% static 'app/img/ico/ds.png' %}" class="img-fluid" width="60" height="60"  id="redes" alt="facebook">
                </a>   
            </div>

            <div class="col-4 order-2" id="texto-redes">
                <img src="{% static 'app/img/logo2.png' %}" width="300" class="img-fluid " alt="">
            </div>

            <div class="col-4 order-3">
                <a href="https://www.instagram.com/victorfavianoo/" target="_blank">
                    <img src="{% static 'app/img/ico/insta.png' %}" class="img-fluid" width="60" height="60" id="redes" alt="instagram">
                </a> 
            </div>
            
        </div>
    </footer>
   
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title":"Felicitaciones",
                    "text":"{{m}}",
                    "icon":"success"
                })
            </script>
        {% endfor %}
    {% endif %}

    {% block js %}

    {%endblock%}
</body>
</html>

{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}

app/templates/app/contacto.html
{% extends 'app/base.html'%}

{% load static %}

{%block js%}

{%endblock%}

{%block css%}
<link rel="stylesheet" href="{% static 'app/css/estilos.css'%}">
<link rel="stylesheet" href="{% static 'app/css/estilo_form.css'%}">
{%endblock%}

{% block contenido%}

{% load crispy_forms_tags %}
<br>
<br>
<div class="container  mt-5 pt-5">
    <div class="row">
        <div class="col-md-5  text-white text-md-start" id="contactame">
            <img src="{% static 'app/img/logos/contacto.png' %}" id="foto-contacto"alt="" />

        </div>
        <div class="formu col-md-6">
            <div class="" id = "estilo-form">
                <form id="contact-formulario" method="POST" action="#" class="contact-form">
                    {% csrf_token %}
                    {{ form |crispy }}
                    <div class="form-group d-flex justify-content-center">
                        <input type="reset" value="Limpiar" class="btn btn-secondary">
                        &nbsp;    
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                {{mensaje}}
            </div>
        </div>
    </div>

{%endblock%}

{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}


app/templates/app/feedbacks.html




{% extends 'app/base.html'%}

{% load static%}
{% block js%}

{%endblock%}

{% block css%}

{%endblock%}

{% load humanize %}

{%block contenido%}
<style>
    .card {
        border: none;
        border-radius: 5px;
        background-color: rgba(255, 255, 255, 0.8); /* Fondo semitransparente */

    }

    .card-body {
        padding: 20px;
    }

    .feedback-author {
        font-style: italic;
        color: #000000;
    }

    .feedback-date {
        color: #000000;
    }

    .text-center h5 {
        margin-top: 0;
        margin-bottom: 10px;
        font-size: 1.2rem;
    }

    .text-center h4 {
        margin-top: 0;
        margin-bottom: 10px;
        font-size: 1.5rem;
    }

    .text-center p {
        margin-top: 0;
        margin-bottom: 10px;
    }


    .container {
        padding: 20px;
    }
</style>
<div class="container img-reglas">
    <div>
        <a href="#">
            <img src="{% static 'app/img/logos/feedbacks.png' %}" class="img-fluid " alt="img-reglas">
        </a>
    </div>
    
    {% if user.is_authenticated %}
    <a href="{% url 'agregar_feedback' %}">
        <button>crear una reseña</button>
    </a>
    {% endif %}
</div>
<div class="container px-4 px-lg-5 mt-5 ">
    <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 justify-content-center">
        {% for p in feedbacks %}
        <div class=" mb-5">
            <div class="card h-100 text-BLACK" id="card-fondo">

                <div class="card-body">
                    <div class="text-center">
                        <h4>{{ p.titulo | title }}</h4>
                        <hr>    
                        <p> {{ p.descripcion }} </p>
                        <hr>
                        <p class="feedback-author"><em>@{{ p.autor }}</em></p>
                        <p class="feedback-date">{{ p.fecha_creado }}</p>
                        
                        
                    </div>
                </div>
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>




{%endblock%}

{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}

app/templates/app/home.html
{% extends 'app/base.html'%}

{% load static %}

{%block js%}

{%endblock%}

{%block css%}

{%endblock%}



{% block contenido%}
<div class="container-fluid mt-5 pt-5">
    <div class="carruselc">
        <section class="carrusel">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                </ol>

                <div class="carousel-inner" >
                    <div class="carousel-item ">
                        <img class="d-block img-fluid" src="{% static 'app/img/imagenes_carrusel/4.jpg' %}" alt="foto 1">
                        </a>
                        <div class="carousel-caption d-none d-md-block" id="foto1">

                        </div>
                    </div>
                    <div class="carousel-item ">
                        <img class="d-block img-fluid" src="{% static 'app/img/imagenes_carrusel/2.jpg' %}" alt="foto 1">
                        </a>
                        <div class="carousel-caption d-none d-md-block" id="foto1">

                        </div>
                    </div>
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'app/img/imagenes_carrusel/3.jpg' %}" alt="fotp 2">
                        </a>
                        <div class="carousel-caption d-none d-md-block" id="foto2">
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'app/img/imagenes_carrusel/1.jpg' %}" alt="foto 3">
                        </a>
                        <div class="carousel-caption d-none d-md-block" id="foto3">
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </section>
    </div>
</div>
    
    <!-- SECCION QUIEN SOY -->
    <br>
<section class="" id="">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6 d-block"  id="">
                <br><br><br>
                <div class="alinear">
                    <img src="{% static 'app/img/mineplus.png' %}" class="rounded-0 " alt="">
                </div>
            </div>
            
            <div class="col-sm-12 col-md-4 align-self-center text-center" id="">
                <br><br><br><br>
                <h1 class="titulo" >¿Quienes Somos?</h1>
                <br>
                <p class="parrafo">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi, voluptatum! Amet vel ipsa impedit laudantium consectetur sed laborum quibusdam! Dolores optio unde iure amet voluptatum harum odit quis mollitia inventore?</p>
            </div>
        </div>
    </div>
</section>
<div class="container nav justify-content-center my-5">
    <div class="row">
        <div class="container responsive-video nav justify-content-center col-12 order-1">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/IlK9SxFqYGg?si=jBqOeFqKAmfmsEQo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </iframe>
        </div>
    </div>
    
</div>


{% endblock %}

{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}

app/templates/app/reglas.html
{% extends 'app/base.html'%}

{% load static %}

{% block js%}

{%endblock%}

{% block css%}

{%endblock%}

{% block contenido%}

<div class="container img-reglas">
    <div>
        <a href="#">
            <img src="{% static 'app/img/logos/reglas.png' %}" class="img-fluid " alt="img-reglas">
        </a>
    </div>

</div>





<div class="container containerreglas">
    <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                    Reglas de Discord
                </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <ul>
                        <li>🡆 Respeto mutuo entre todos los miembros.</li>
                        <li>🡆 No se permite el uso de lenguaje ofensivo o insultos.</li>
                        <li>🡆 Está prohibido el spam o publicidad no autorizada.</li>
                        <li>🡆 No se permite compartir contenido inapropiado o NSFW.</li>
                        <li>🡆 Evita discusiones sobre temas controvertidos (política, religión, etc.).</li>
                        <li>🡆 Sigue las instrucciones de los moderadores y administradores.</li>
                        <li>🡆 No compartir información personal sin consentimiento.</li>
                        <li>🡆 Utiliza los canales apropiados para cada tipo de conversación.</li>
                        <li>🡆 Reporta cualquier comportamiento inapropiado a los moderadores.</li>
                        <li>🡆 Diviértete y mantén un ambiente amigable y acogedor.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    Reglas del Modo Supervivencia
                </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <ul>
                        <li>🡆 No está permitido el uso de hacks o mods que otorguen ventajas injustas.</li>
                        <li>🡆 No se permite el griefeo o destrucción de construcciones de otros jugadores.</li>
                        <li>🡆 El PvP está permitido solo en áreas designadas o con el consentimiento de ambos jugadores.</li>
                        <li>🡆 No está permitido robar recursos o pertenencias de otros jugadores.</li>
                        <li>🡆 Respeta el entorno y no construyas estructuras que causen lag o problemas al servidor.</li>
                        <li>🡆 No abuses de bugs o glitches del juego.</li>
                        <li>🡆 Sigue las instrucciones de los administradores y moderadores del servidor.</li>
                        <li>🡆 Construye y juega de manera responsable, pensando en el bienestar de la comunidad.</li>
                        <li>🡆 Participa en eventos y actividades del servidor de manera justa y deportiva.</li>
                        <li>🡆 Reporta cualquier comportamiento inapropiado o infracciones a las reglas a los moderadores.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    Reglas del Modo PvP
                </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <ul>
                        <li>🡆 No está permitido el uso de hacks o mods que otorguen ventajas injustas en el combate.</li>
                        <li>🡆 A tus oponentes, no insultes ni uses lenguaje ofensivo durante las partidas.</li>
                        <li>🡆 Está permitido el teaming (aliarse con otros jugadores) en modos donde está prohibido.</li>
                        <li>🡆 De manera justa y no abuses de bugs o glitches.</li>
                        <li>🡆 El spawn-killing (matar jugadores recién aparecidos) en áreas de respawn.</li>
                        <li>🡆 De manera deportiva y respeta las reglas de cada modalidad de PvP.</li>
                        <li>🡆 Hagas trampas ni uses exploits para obtener ventajas.</li>
                        <li>🡆 Las instrucciones de los moderadores y administradores del servidor.</li>
                        <li>🡆 Cualquier comportamiento inapropiado o trampas a los moderadores.</li>
                        <li>🡆 Y mantén un ambiente competitivo pero respetuoso.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingFour">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
                    Reglas del Modo Skyblock
                </button>
            </h2>
            <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <ul>
                        <li>🡆 No está permitido el uso de hacks o mods que otorguen ventajas injustas.</li>
                        <li>🡆 No robar recursos o pertenencias de otros jugadores.</li>
                        <li>🡆 Construye de manera responsable, evitando estructuras que causen lag o problemas al servidor.</li>
                        <li>🡆 No abuses de bugs o glitches del juego.</li>
                        <li>🡆 El comercio de items debe ser justo y sin estafas.</li>
                        <li>🡆 Respeta a los otros jugadores y sus islas.</li>
                        <li>🡆 Sigue las instrucciones de los administradores y moderadores del servidor.</li>
                        <li>🡆 Participa en eventos y actividades de Skyblock de manera justa y deportiva.</li>
                        <li>🡆 Reporta cualquier comportamiento inapropiado o infracciones a las reglas a los moderadores.</li>
                        <li>🡆 Disfruta del juego y contribuye a una comunidad amigable y cooperativa.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<br><br>

{%endblock%}


{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}

app/templates/app/tienda.html
{% extends 'app/base.html'%}

{% load static%}
{% block js%}

{%endblock%}

{% block css%}

{%endblock%}

{% load humanize %}

{%block contenido%}
<br><br>
<div class="container px-4 px-lg-5 mt-5">
    <h1 class="titulo text-center">Tienda</h1>
    <hr>
    <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for p in productos %}
        <div class=" mb-5">
            <div class="card h-100 text-BLACK" id="card-fondo">
                {% if p.imagen %}
                <img class="card-img-top" src="{{ p.imagen.url }}" alt="imagen-producto" />
                {% endif %}
                <div class="card-body">
                    <div class="text-center">
                        <h5 class="fw-bolder">{{ p.marca | capfirst }}</h5>
                        <h4>{{ p.nombre | title }}</h4>
                        <h4>{{ p.color | title }}</h4>
                        <p> {{ p.descripcion }} </p>
                        <h4 class="fw-bolder">$ {{ p.precio | intcomma}}</h4>
                        
                    </div>
                </div>
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>



{%endblock%}


{% comment %} 
----------------------------------
            Chuly
    GitHub: https://github.com/victoryanezn
    Discord: chuly2005#0
---------------------------------- 
{% endcomment %}